package de.rwth.i5.kinectvision.robot.serialconnection;

/**
 * This interface is for handling the data generated by the robot.
 */
public interface RobotHandler {

    void onAxisData(double[] angles);

    void setAxis(int i, double axisValue);
}
